#build language for configuration 
language: python

#python versions to try
python:
  - 3.9
  - 3.8

#only evaluate the main branch
branches:
  only:
    - main

#set up environment
install:
  - pip install coverage
  - pip install flake8
  - pip install -r requirements.txt

#run commands before main script
before_script:
  - "flake8 textsimilarity"

#run unittests
script:
  - coverage run -m unittest discover 

#generate report
after_success:
  - coverage report